In [1]:
import pypowsybl as pp
import numpy as np
network = pp.network.create_ieee14()
net = network

In [ ]:
network.set

In [4]:
df_gen = network.get_generators() 

In [12]:
df_gen

name energy_source  target_p   min_p   max_p          min_q  \
id                                                                 
B1-G              OTHER     232.4 -9999.0  9999.0 -1.797693e+308   
B2-G              OTHER      40.0 -9999.0  9999.0  -4.000000e+01   
B3-G              OTHER       0.0 -9999.0  9999.0   0.000000e+00   
B6-G              OTHER       0.0 -9999.0  9999.0  -6.000000e+00   
B8-G              OTHER       0.0 -9999.0  9999.0  -6.000000e+00   

              max_q  rated_s reactive_limits_kind  target_v  target_q  \
id                                                                      
B1-G  1.797693e+308      NaN              MIN_MAX   143.100     -16.9   
B2-G   5.000000e+01      NaN              MIN_MAX   141.075      42.4   
B3-G   4.000000e+01      NaN              MIN_MAX   136.350      23.4   
B6-G   2.400000e+01      NaN              MIN_MAX    12.840      12.2   
B8-G   2.400000e+01      NaN              MIN_MAX    21.800      17.4   

      voltage_regulator_on regulated_element_id   p   q   i voltage_level_id  \
id                                                                             
B1-G                  True                      NaN NaN NaN              VL1   
B2-G                  True                      NaN NaN NaN              VL2   
B3-G                  True                      NaN NaN NaN              VL3   
B6-G                  True                      NaN NaN NaN              VL6   
B8-G                  True                      NaN NaN NaN              VL8   

     bus_id  connected  
id                      
B1-G  VL1_0       True  
B2-G  VL2_0       True  
B3-G  VL3_0       True  
B6-G  VL6_0       True  
B8-G  VL8_0       True

In [11]:
net.get_voltage_levels().loc[df_gen["voltage_level_id"].values]["nominal_v"].values

array([135., 135., 135.,  12.,  20.])

In [17]:
bus_df = net.get_buses()
bus_df["bus_id"] = np.arange(bus_df.shape[0])

In [19]:
bus_df.loc[df_gen["bus_id"]]["bus_id"].values

array([0, 1, 2, 5, 7])

In [44]:
bus_df

name    v_mag  v_angle  connected_component  synchronous_component  \
id                                                                          
VL1_0        143.100     0.00                    0                      0   
VL2_0        141.075    -4.98                    0                      0   
VL3_0        136.350   -12.72                    0                      0   
VL4_0        137.565   -10.33                    0                      0   
VL5_0        137.700    -8.78                    0                      0   
VL6_0         12.840   -14.22                    0                      0   
VL7_0         14.868   -13.37                    0                      0   
VL8_0         21.800   -13.36                    0                      0   
VL9_0         12.672   -14.94                    0                      0   
VL10_0        12.612   -15.10                    0                      0   
VL11_0        12.684   -14.79                    0                      0   
VL12_0        12.660   -15.07                    0                      0   
VL13_0        12.600   -15.16                    0                      0   
VL14_0        12.432   -16.04                    0                      0   

       voltage_level_id  bus_id  
id                               
VL1_0               VL1       0  
VL2_0               VL2       1  
VL3_0               VL3       2  
VL4_0               VL4       3  
VL5_0               VL5       4  
VL6_0               VL6       5  
VL7_0               VL7       6  
VL8_0               VL8       7  
VL9_0               VL9       8  
VL10_0             VL10       9  
VL11_0             VL11      10  
VL12_0             VL12      11  
VL13_0             VL13      12  
VL14_0             VL14      13

In [20]:

df_load = net.get_loads()

In [21]:
df_load

name       type    p0    q0   p   q   i voltage_level_id  bus_id  \
id                                                                       
B2-L        UNDEFINED  21.7  12.7 NaN NaN NaN              VL2   VL2_0   
B3-L        UNDEFINED  94.2  19.0 NaN NaN NaN              VL3   VL3_0   
B4-L        UNDEFINED  47.8  -3.9 NaN NaN NaN              VL4   VL4_0   
B5-L        UNDEFINED   7.6   1.6 NaN NaN NaN              VL5   VL5_0   
B6-L        UNDEFINED  11.2   7.5 NaN NaN NaN              VL6   VL6_0   
B9-L        UNDEFINED  29.5  16.6 NaN NaN NaN              VL9   VL9_0   
B10-L       UNDEFINED   9.0   5.8 NaN NaN NaN             VL10  VL10_0   
B11-L       UNDEFINED   3.5   1.8 NaN NaN NaN             VL11  VL11_0   
B12-L       UNDEFINED   6.1   1.6 NaN NaN NaN             VL12  VL12_0   
B13-L       UNDEFINED  13.5   5.8 NaN NaN NaN             VL13  VL13_0   
B14-L       UNDEFINED  14.9   5.0 NaN NaN NaN             VL14  VL14_0   

       connected  
id                
B2-L        True  
B3-L        True  
B4-L        True  
B5-L        True  
B6-L        True  
B9-L        True  
B10-L       True  
B11-L       True  
B12-L       True  
B13-L       True  
B14-L       True

In [23]:
df_gen["target_p"].sum()

272.4

In [24]:
df_load["p0"].sum()

259.0

In [27]:
df_line = net.get_lines()

In [30]:
bus_df.loc[df_line["bus1_id"].values]["bus_id"].values

array([ 0,  0,  1,  1,  1,  2,  3,  5,  5,  5,  6,  6,  8,  8,  9, 11, 12])

In [29]:
line_h = 0.5 * (df_line["g1"].values + 1j*df_line["b1"] + df_line["g2"].values + 1j*df_line["b2"])

In [31]:
df_trafo = net.get_2_windings_transformers()

In [35]:
df_trafo["g"].values + 1j*df_trafo["b"].values

array([0.+0.j, 0.+0.j, 0.+0.j])

In [36]:
df_trafo

name    r         x    g    b  rated_u1  rated_u2  rated_s  p1  q1  i1  \
id                                                                              
T4-7-1       0.0  0.409875  0.0  0.0   132.030      14.0      NaN NaN NaN NaN   
T4-9-1       0.0  0.800899  0.0  0.0   130.815      12.0      NaN NaN NaN NaN   
T5-6-1       0.0  0.362909  0.0  0.0   125.820      12.0      NaN NaN NaN NaN   

        p2  q2  i2 voltage_level1_id voltage_level2_id bus1_id bus2_id  \
id                                                                       
T4-7-1 NaN NaN NaN               VL4               VL7   VL4_0   VL7_0   
T4-9-1 NaN NaN NaN               VL4               VL9   VL4_0   VL9_0   
T5-6-1 NaN NaN NaN               VL5               VL6   VL5_0   VL6_0   

        connected1  connected2  
id                              
T4-7-1        True        True  
T4-9-1        True        True  
T5-6-1        True        True

In [40]:
net.get_shunt_compensators()

name    g         b model_type  max_section_count  section_count  \
id                                                                       
B9-SH       0.0  0.131944     LINEAR                  1              1   

       voltage_regulation_on  target_v  target_deadband regulating_bus_id  \
id                                                                          
B9-SH                  False       NaN              NaN             VL9_0   

         p          q           i voltage_level_id bus_id  connected  
id                                                                    
B9-SH  0.0 -21.184844  965.267236              VL9  VL9_0       True

In [42]:
net.get_shunt_compensators()

name    g         b model_type  max_section_count  section_count  \
id                                                                       
B9-SH       0.0  0.131944     LINEAR                  1              1   

       voltage_regulation_on  target_v  target_deadband regulating_bus_id   p  \
id                                                                              
B9-SH                  False       NaN              NaN             VL9_0 NaN   

        q   i voltage_level_id bus_id  connected  
id                                                
B9-SH NaN NaN              VL9  VL9_0       True

In [38]:
import pypowsybl.loadflow as lf
lf.get_provider_names()

['DynaFlow', 'OpenLoadFlow']

In [55]:
lf.run_dc(net)

[ComponentResult(connected_component_num=0, synchronous_component_num=0, status=CONVERGED, iteration_count=0, slack_bus_id='VL1_0', slack_bus_active_power_mismatch=-13.399999999999942, distributed_active_power=nan)]

In [57]:
net.get_buses()

name  v_mag    v_angle  connected_component  synchronous_component  \
id                                                                          
VL1_0          NaN   0.000000                    0                      0   
VL2_0          NaN  -5.012011                    0                      0   
VL3_0          NaN -12.953663                    0                      0   
VL4_0          NaN -10.583667                    0                      0   
VL5_0          NaN  -9.093894                    0                      0   
VL6_0          NaN -14.852079                    0                      0   
VL7_0          NaN -13.907055                    0                      0   
VL8_0          NaN -13.907055                    0                      0   
VL9_0          NaN -15.694689                    0                      0   
VL10_0         NaN -15.974123                    0                      0   
VL11_0         NaN -15.618850                    0                      0   
VL12_0         NaN -15.967077                    0                      0   
VL13_0         NaN -16.139704                    0                      0   
VL14_0         NaN -17.188288                    0                      0   

       voltage_level_id  
id                       
VL1_0               VL1  
VL2_0               VL2  
VL3_0               VL3  
VL4_0               VL4  
VL5_0               VL5  
VL6_0               VL6  
VL7_0               VL7  
VL8_0               VL8  
VL9_0               VL9  
VL10_0             VL10  
VL11_0             VL11  
VL12_0             VL12  
VL13_0             VL13  
VL14_0             VL14

In [46]:
df_gen

name energy_source  target_p   min_p   max_p          min_q  \
id                                                                 
B1-G              OTHER     232.4 -9999.0  9999.0 -1.797693e+308   
B2-G              OTHER      40.0 -9999.0  9999.0  -4.000000e+01   
B3-G              OTHER       0.0 -9999.0  9999.0   0.000000e+00   
B6-G              OTHER       0.0 -9999.0  9999.0  -6.000000e+00   
B8-G              OTHER       0.0 -9999.0  9999.0  -6.000000e+00   

              max_q  rated_s reactive_limits_kind  target_v  target_q  \
id                                                                      
B1-G  1.797693e+308      NaN              MIN_MAX   143.100     -16.9   
B2-G   5.000000e+01      NaN              MIN_MAX   141.075      42.4   
B3-G   4.000000e+01      NaN              MIN_MAX   136.350      23.4   
B6-G   2.400000e+01      NaN              MIN_MAX    12.840      12.2   
B8-G   2.400000e+01      NaN              MIN_MAX    21.800      17.4   

      voltage_regulator_on regulated_element_id   p   q   i voltage_level_id  \
id                                                                             
B1-G                  True                      NaN NaN NaN              VL1   
B2-G                  True                      NaN NaN NaN              VL2   
B3-G                  True                      NaN NaN NaN              VL3   
B6-G                  True                      NaN NaN NaN              VL6   
B8-G                  True                      NaN NaN NaN              VL8   

     bus_id  connected  
id                      
B1-G  VL1_0       True  
B2-G  VL2_0       True  
B3-G  VL3_0       True  
B6-G  VL6_0       True  
B8-G  VL8_0       True

In [52]:
net.get_generators()["p"].sum()

-272.4

In [53]:
net.get_loads()["p"].sum()

259.0

In [59]:
net.get_lines()

name          r          x   g1        b1   g2        b2  p1  q1  i1  \
id                                                                              
L1-2-1          3.532005  10.783732  0.0  0.000145  0.0  0.000145 NaN NaN NaN   
L1-5-1          9.846967  40.649040  0.0  0.000135  0.0  0.000135 NaN NaN NaN   
L2-3-1          8.563927  36.080033  0.0  0.000120  0.0  0.000120 NaN NaN NaN   
L2-4-1         10.590547  32.134320  0.0  0.000093  0.0  0.000093 NaN NaN NaN   
L2-5-1         10.379137  31.689630  0.0  0.000095  0.0  0.000095 NaN NaN NaN   
L3-4-1         12.212573  31.170217  0.0  0.000035  0.0  0.000035 NaN NaN NaN   
L4-5-1          2.433038   7.674548  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L6-11-1         0.136771   0.286416  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L6-12-1         0.176990   0.368366  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L6-13-1         0.095256   0.187589  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L7-8-1          0.000000   0.493220  0.0 -0.868925  0.0  0.608248 NaN NaN NaN   
L7-9-1          0.000000   0.184817  0.0  0.772966  0.0 -0.901794 NaN NaN NaN   
L9-10-1         0.045806   0.121680  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L9-14-1         0.183038   0.389347  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L10-11-1        0.118152   0.276581  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L12-13-1        0.318125   0.287827  0.0  0.000000  0.0  0.000000 NaN NaN NaN   
L13-14-1        0.246139   0.501149  0.0  0.000000  0.0  0.000000 NaN NaN NaN   

          p2  q2  i2 voltage_level1_id voltage_level2_id bus1_id bus2_id  \
id                                                                         
L1-2-1   NaN NaN NaN               VL1               VL2   VL1_0   VL2_0   
L1-5-1   NaN NaN NaN               VL1               VL5   VL1_0   VL5_0   
L2-3-1   NaN NaN NaN               VL2               VL3   VL2_0   VL3_0   
L2-4-1   NaN NaN NaN               VL2               VL4   VL2_0   VL4_0   
L2-5-1   NaN NaN NaN               VL2               VL5   VL2_0   VL5_0   
L3-4-1   NaN NaN NaN               VL3               VL4   VL3_0   VL4_0   
L4-5-1   NaN NaN NaN               VL4               VL5   VL4_0   VL5_0   
L6-11-1  NaN NaN NaN               VL6              VL11   VL6_0  VL11_0   
L6-12-1  NaN NaN NaN               VL6              VL12   VL6_0  VL12_0   
L6-13-1  NaN NaN NaN               VL6              VL13   VL6_0  VL13_0   
L7-8-1   NaN NaN NaN               VL7               VL8   VL7_0   VL8_0   
L7-9-1   NaN NaN NaN               VL7               VL9   VL7_0   VL9_0   
L9-10-1  NaN NaN NaN               VL9              VL10   VL9_0  VL10_0   
L9-14-1  NaN NaN NaN               VL9              VL14   VL9_0  VL14_0   
L10-11-1 NaN NaN NaN              VL10              VL11  VL10_0  VL11_0   
L12-13-1 NaN NaN NaN              VL12              VL13  VL12_0  VL13_0   
L13-14-1 NaN NaN NaN              VL13              VL14  VL13_0  VL14_0   

          connected1  connected2  
id                                
L1-2-1          True        True  
L1-5-1          True        True  
L2-3-1          True        True  
L2-4-1          True        True  
L2-5-1          True        True  
L3-4-1          True        True  
L4-5-1          True        True  
L6-11-1         True        True  
L6-12-1         True        True  
L6-13-1         True        True  
L7-8-1          True        True  
L7-9-1          True        True  
L9-10-1         True        True  
L9-14-1         True        True  
L10-11-1        True        True  
L12-13-1        True        True  
L13-14-1        True        True

In [62]:
import pandapower.networks as pn
pn.case14().sn_mva

100